# Generated by Django 2.2 on 2022-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('tildeE', models.CharField(max_length=1000)),
                ('tildeZ', models.CharField(max_length=1000)),
                ('u', models.CharField(default='0', max_length=1000)),
                ('IsJoin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.CharField(max_length=1000)),
                ('Q', models.CharField(max_length=1000)),
                ('X', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.CharField(max_length=1000)),
                ('G', models.CharField(max_length=1000)),
                ('H', models.CharField(max_length=1000)),
                ('Z', models.CharField(max_length=1000)),
                ('L', models.CharField(max_length=1000)),
                ('L1', models.CharField(max_length=1000)),
                ('L2', models.CharField(max_length=1000)),
                ('LG', models.CharField(max_length=1000)),
                ('K', models.CharField(max_length=1000)),
                ('ESP', models.CharField(max_length=1000)),
                ('Y', models.CharField(max_length=1000)),
            ],
        ),
    ]
